---
title: "heifer_parlor_behavior_script"
author: "Hannah Phillips"
date: "February 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = F}
library(readxl)
library(tidyverse)

library(utils)
library(NSM3)
library(plyr)
library(lubridate)
library(BSDA)
library(NSM3) #RFPW
library(clusrank)


dat = read_excel("heifer_behavior_tidy.xlsx") %>% 
  mutate_at(vars(ID, Herd, Trt, Breed, Season), as.factor)
  

```

# Parlor behavior
```{r}
Train = subset(dat, Trt == "Train" & !is.na(Behavior))
Control = subset(dat, Trt == "Control" & !is.na(Behavior))
#y =  subset(x, Behavior != "NA")

#plot
{
par(mfrow=c(1,1))

hist(dat$Behavior, xlab = "Value", freq = F)
lines(density(Train$Behavior), col="blue", lwd=3)
lines(density(Control$Behavior), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$Behavior)$obs.stat) # not symetric
1- pnorm(RFPW(Train$Behavior)$obs.stat)

pnorm(RFPW(Control$Behavior)$obs.stat) # symetric
1- pnorm(RFPW(Control$Behavior)$obs.stat)

wilcox.test(Train$Behavior, Control$Behavior, paired = F)
SIGN.test(Train$Behavior, conf.int = T)
wilcox.test(Control$Behavior, conf.int = T)

# tests equal distribution functions
ks.test(Train$Behavior, Control$Behavior, exact = NULL)

# tests equal variance
Train$BehaviorScaled = Train$Behavior + median(Control$Behavior) - median(Train$Behavior)
ansari.test(Train$BehaviorScaled, Control$Behavior)
var(Control$Behavior)
var(Train$Behavior)
```

# Entry behavior
```{r}

Train = subset(x, Trt == "Train" & `Entry score` != "NA" )
Control = subset(x, Trt == "Control" & `Entry score` != "NA")

## test of asymmetry
test = RFPW(Train$`Entry score`) 
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$`Entry score`)
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$`Entry score`, Control$`Entry score`, paired = F)
wilcox.test(Train$`Entry score`, conf.int = T)
wilcox.test(Control$`Entry score`, conf.int = T)

# tests equal distribution functions
ks.test(Train$`Entry score`, Control$`Entry score`, exact = NULL)

# tests equal location and scale
pLepage(Train$`Entry score`, Control$`Entry score`)

# tests equal variance p = 0.01
mDif = median(Control$`Entry score`) - median(Train$`Entry score`)
Train$EntryScoreScaled = Train$`Entry score` + mDif

ansari.test(Train$EntryScoreScaled, Control$`Entry score`, conf.level = 0.95, paired = F)
var(Control$`Entry score`)
var(Train$`Entry score`)
```

# avg behavior score
```{r}
Train = subset(dat, Trt == "Train" & !is.na(avgScore))
Control = subset(dat, Trt == "Control" & !is.na(avgScore))

#plot
{
par(mfrow=c(1,1))

hist(dat$avgScore, xlab = "Value", freq = F)
lines(density(Train$avgScore), col="blue", lwd=3)
lines(density(Control$avgScore), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$avgScore)$obs.stat) # not symetric
1- pnorm(RFPW(Train$avgScore)$obs.stat)

pnorm(RFPW(Control$avgScore)$obs.stat) # symetric
1- pnorm(RFPW(Control$avgScore)$obs.stat)

wilcox.test(Train$avgScore, Control$avgScore, paired = F)
SIGN.test(Train$avgScore, conf.int = T)
wilcox.test(Control$avgScore, conf.int = T)

# tests equal distribution functions
ks.test(Train$avgScore, Control$avgScore, exact = NULL)

# tests equal variance
Train$scoreAvgScaled = Train$avgScore + median(Control$avgScore) - median(Train$avgScore)
ansari.test(Train$scoreAvgScaled, Control$avgScore)
var(Control$avgScore)
var(Train$avgScore)
```

# multiplied behavior score
```{r}
Train = subset(dat, Trt == "Train" & !is.na(multipliedScore))
Control = subset(dat, Trt == "Control" & !is.na(multipliedScore))

#plot
{
par(mfrow=c(1,1))

hist(dat$multipliedScore, xlab = "Value", freq = F)
lines(density(Train$multipliedScore), col="blue", lwd=3)
lines(density(Control$multipliedScore), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$multipliedScore)$obs.stat) # not symetric
1- pnorm(RFPW(Train$multipliedScore)$obs.stat)

pnorm(RFPW(Control$multipliedScore)$obs.stat) # symetric
1- pnorm(RFPW(Control$multipliedScore)$obs.stat)

wilcox.test(Train$multipliedScore, Control$multipliedScore, paired = F)
SIGN.test(Train$multipliedScore, conf.int = T)
wilcox.test(Control$multipliedScore, conf.int = T)

# tests equal distribution functions
ks.test(Train$multipliedScore, Control$multipliedScore, exact = NULL)

# tests equal variance
Train$multipliedScoreScaled = Train$multipliedScore + median(Control$multipliedScore) - median(Train$multipliedScore)
ansari.test(Train$multipliedScoreScaled, Control$multipliedScore)
var(Control$multipliedScore)
var(Train$multipliedScore)
```

# kick-stomp
```{r}
Train = subset(dat, Trt == "Train" & !is.na(kickStomp))
Control = subset(dat, Trt == "Control" & !is.na(kickStomp))

#plot
{
par(mfrow=c(1,1))

hist(dat$kickStomp, xlab = "Value", freq = F)
lines(density(Train$kickStomp), col="blue", lwd=3)
lines(density(Control$kickStomp), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$kickStomp)$obs.stat) # not symetric
1- pnorm(RFPW(Train$kickStomp)$obs.stat)

pnorm(RFPW(Control$kickStomp)$obs.stat) # symetric
1- pnorm(RFPW(Control$kickStomp)$obs.stat)

wilcox.test(Train$kickStomp, Control$kickStomp, paired = F)
SIGN.test(Train$kickStomp, conf.int = T)
wilcox.test(Control$kickStomp, conf.int = T)

# tests equal distribution functions
ks.test(Train$kickStomp, Control$kickStomp, exact = NULL)

# tests equal variance
Train$kickStompScaled = Train$kickStomp + median(Control$kickStomp) - median(Train$kickStomp)
ansari.test(Train$kickStompScaled, Control$kickStomp)
var(Control$kickStomp)
var(Train$kickStomp)
```

# kick-stomp-milker
```{r}
Train = subset(dat, Trt == "Train" & !is.na(kickStompMilker))
Control = subset(dat, Trt == "Control" & !is.na(kickStompMilker))

#plot
{
par(mfrow=c(1,1))

hist(dat$kickStompMilker, xlab = "Value", freq = F)
lines(density(Train$kickStompMilker), col="blue", lwd=3)
lines(density(Control$kickStompMilker), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$kickStompMilker)$obs.stat) # not symetric
1- pnorm(RFPW(Train$kickStompMilker)$obs.stat)

pnorm(RFPW(Control$kickStompMilker)$obs.stat) # symetric
1- pnorm(RFPW(Control$kickStompMilker)$obs.stat)

wilcox.test(Train$kickStompMilker, Control$kickStompMilker, paired = F)
SIGN.test(Train$kickStompMilker, conf.int = T)
wilcox.test(Control$kickStompMilker, conf.int = T)

# tests equal distribution functions
ks.test(Train$kickStompMilker, Control$kickStompMilker, exact = NULL)

# tests equal variance
Train$kickStompMilkerScaled = Train$kickStompMilker + median(Control$kickStompMilker) - median(Train$kickStompMilker)
ansari.test(Train$kickStompMilkerScaled, Control$kickStompMilker)
var(Control$kickStompMilker)
var(Train$kickStompMilker)
```

# avg number of bacteria types found per quarter
```{r}
Train = subset(dat, Trt == "Train" & !is.na(noBacTypes))
Control = subset(dat, Trt == "Control" & !is.na(noBacTypes))

#plot
{
par(mfrow=c(1,1))

hist(dat$noBacTypes, xlab = "Value", freq = F)
lines(density(Train$noBacTypes), col="blue", lwd=3)
lines(density(Control$noBacTypes), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$noBacTypes)$obs.stat) # symetric
1- pnorm(RFPW(Train$noBacTypes)$obs.stat)

pnorm(RFPW(Control$noBacTypes)$obs.stat) # symetric
1- pnorm(RFPW(Control$noBacTypes)$obs.stat)

wilcox.test(Train$noBacTypes, Control$noBacTypes, paired = F)
wilcox.test(Train$noBacTypes, conf.int = T)
wilcox.test(Control$noBacTypes, conf.int = T)

# tests equal distribution functions
ks.test(Train$noBacTypes, Control$noBacTypes, exact = NULL)

# tests equal variance
Train$noBacTypesScaled = Train$noBacTypes + median(Control$noBacTypes) - median(Train$noBacTypes)
ansari.test(Train$noBacTypesScaled, Control$noBacTypes)
var(Control$noBacTypes)
var(Train$noBacTypes)
```

# proportion of quarters with bacteria present
```{r}
Train = subset(dat, Trt == "Train" & !is.na(BacPresent))
Control = subset(dat, Trt == "Control" & !is.na(BacPresent))

#plot
{
par(mfrow=c(1,1))

hist(dat$BacPresent, xlab = "Value", freq = F)
lines(density(Train$BacPresent), col="blue", lwd=3)
lines(density(Control$BacPresent), col="red", lwd=3)

legend(title = "Distribution", "topright", legend=c("Train","Control"), col=c("blue","red"), lty=1, lwd = 3)
}

## test of asymmetry
pnorm(RFPW(Train$BacPresent)$obs.stat) # not symetric
1- pnorm(RFPW(Train$BacPresent)$obs.stat)

pnorm(RFPW(Control$BacPresent)$obs.stat) # not symetric
1- pnorm(RFPW(Control$BacPresent)$obs.stat)

wilcox.test(Train$BacPresent, Control$BacPresent, paired = F)
SIGN.test(Train$BacPresent, conf.int = T)
SIGN.test(Control$noBacTypes, conf.int = T)

# tests equal distribution functions
ks.test(Train$BacPresent, Control$BacPresent, exact = NULL)

# tests equal variance
Train$BacPresentScaled = Train$BacPresent + median(Control$BacPresent) - median(Train$BacPresent)
ansari.test(Train$BacPresentScaled, Control$BacPresent)
var(Control$BacPresent)
var(Train$BacPresent)
```

# Stomps 
```{r}
Train = subset(x, Trt == "Train" & Stomp != "NA" )
Control = subset(x, Trt == "Control" & Stomp != "NA")

## test of asymmetry
test =RFPW(Train$Stomp) # not symmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Stomp)
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Stomp, Control$Stomp, paired = F)
SIGN.test(Train$Stomp, conf.int = T)
wilcox.test(Control$Stomp, conf.int = T)

# tests equal distribution functions
ks.test(Train$Stomp, Control$Stomp, exact = NULL)

# tests equal location and scale
pLepage(Train$Stomp, Control$Stomp)

# tests equal variance 
mDif = median(Control$Stomp) - median(Train$Stomp)
Train$StompScaled = Train$Stomp + mDif

ansari.test(Train$StompScaled, Control$Stomp, conf.level = 0.95, paired = F)
var(Control$Stomp)
var(Train$Stomp)
```

# Kick 
```{r}
Train = subset(x, Trt == "Train" & Kick != "NA" )
Control = subset(x, Trt == "Control" & Kick != "NA")

## test of asymmetry
test = RFPW(Train$Kick) # not symmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Kick) # not symmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Kick, Control$Kick, paired = F)
SIGN.test(Train$Kick, conf.int = T)
SIGN.test(Control$Kick, conf.int = T)

# tests equal distribution functions
ks.test(Train$Kick, Control$Kick, exact = NULL)

# tests equal location and scale
pLepage(Train$Kick, Control$Kick)

# tests equal variance 
mDif = median(Control$Kick) - median(Train$Kick)
Train$KickScaled = Train$Kick + mDif

ansari.test(Train$KickScaled, Control$Kick, conf.level = 0.95, paired = F)
var(Control$Kick)
var(Train$Kick)
```


# Defecate 
```{r}
Train = subset(x, Trt == "Train" & Defecate != "NA" )
Control = subset(x, Trt == "Control" & Defecate != "NA")

## test of asymmetry
test = RFPW(Train$Defecate)
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Defecate)
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Defecate, Control$Defecate, paired = F)
wilcox.test(Train$Defecate, conf.int = T)
wilcox.test(Control$Defecate, conf.int = T)

# tests equal distribution functions
ks.test(Train$Defecate, Control$Defecate, exact = NULL)

# tests equal location and scale
pLepage(Train$Defecate, Control$Defecate)

# tests equal variance 
mDif = median(Control$Defecate) - median(Train$Defecate)
Train$DefecateScaled = Train$Defecate + mDif

ansari.test(Train$DefecateScaled, Control$Defecate, conf.level = 0.95, paired = F)
var(Control$Defecate)
var(Train$Defecate)
```

#Milker
```{r}
Train = subset(x, Trt == "Train" & Milker != "NA" )
Control = subset(x, Trt == "Control" & Milker != "NA")

## test of asymmetry
test = RFPW(Train$Milker) #asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Milker) #asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Milker, Control$Milker, paired = F)
SIGN.test(Train$Milker, conf.int = T)
SIGN.test(Control$Milker, conf.int = T)

# tests equal distribution functions
ks.test(Train$Milker, Control$Milker, exact = NULL)

# tests equal location and scale
pLepage(Train$Milker, Control$Milker)

# tests equal variance 
mDif = median(Control$Milker) - median(Train$Milker)
Train$MilkerScaled = Train$Milker + mDif

ansari.test(Train$MilkerScaled, Control$Milker, conf.level = 0.95, paired = F)
var(Control$Milker)
var(Train$Milker)
```


# Swollen
```{r}
Train = subset(x, Trt == "Train" & Swollen != "NA" )
Control = subset(x, Trt == "Control" & Swollen != "NA")

## test of asymmetry
test = RFPW(Train$Swollen) #asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Swollen) #asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Swollen, Control$Swollen, paired = F)
SIGN.test(Train$Swollen, conf.int = T)
SIGN.test(Control$Swollen, conf.int = T)

# tests equal distribution functions
ks.test(Train$Swollen, Control$Swollen, exact = NULL)

# tests equal location and scale
pLepage(Train$Swollen, Control$Swollen)

# tests equal variance 
mDif = median(Control$Swollen) - median(Train$Swollen)
Train$SwollenScaled = Train$Swollen + mDif

ansari.test(Train$SwollenScaled, Control$Swollen, conf.level = 0.95, paired = F)
var(Control$Swollen)
var(Train$Swollen)
```

# Mastitis score
```{r}
Train = subset(x, Trt == "Train" & `Mastitis score` != "NA" )
Control = subset(x, Trt == "Control" & `Mastitis score` != "NA")

## test of asymmetry
test = RFPW(Train$`Mastitis score`) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$`Mastitis score`) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$`Mastitis score`, Control$`Mastitis score`, paired = F)
SIGN.test(Train$`Mastitis score`, conf.int = T)
SIGN.test(Control$`Mastitis score`, conf.int = T)

# tests equal distribution functions
ks.test(Train$`Mastitis score`, Control$`Mastitis score`, exact = NULL)

# tests equal location and scale
pLepage(Train$`Mastitis score`, Control$`Mastitis score`)

# tests equal variance 
mDif = median(Control$`Mastitis score`) - median(Train$`Mastitis score`)
Train$MastitisscoreScaled = Train$`Mastitis score` + mDif

ansari.test(Train$MastitisscoreScaled, Control$`Mastitis score`, conf.level = 0.95, paired = F)
var(Control$`Mastitis score`)
var(Train$`Mastitis score`)
```


# Bacteria level
```{r}
Train = subset(x, Trt == "Train" & Level != "NA" )
Control = subset(x, Trt == "Control" & Level != "NA")

## test of asymmetry
test = RFPW(Train$Level) 
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Level) 
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Level, Control$Level, paired = F)
wilcox.test(Train$Level, conf.int = T)
wilcox.test(Control$Level, conf.int = T)

# tests equal distribution functions
ks.test(Train$Level, Control$Level, exact = NULL)

# tests equal location and scale
pLepage(Train$Level, Control$Level)

# tests equal variance 
mDif = median(Control$Level) - median(Train$Level)
Train$LevelScaled = Train$Level + mDif

ansari.test(Train$LevelScaled, Control$Level, conf.level = 0.95, paired = F)
var(Control$Level)
var(Train$Level)
```

# Staph sp
```{r}
Train = subset(x, Trt == "Train" & StaphSpp != "NA" )
Control = subset(x, Trt == "Control" & StaphSpp != "NA")

## test of asymmetry
test = RFPW(Train$StaphSpp) 
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$StaphSpp) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$StaphSpp, Control$StaphSpp, paired = F)
wilcox.test(Train$StaphSpp, conf.int = T)
SIGN.test(Control$StaphSpp, conf.int = T)

# tests equal distribution functions
ks.test(Train$StaphSpp, Control$StaphSpp, exact = NULL)

# tests equal location and scale
pLepage(Train$StaphSpp, Control$StaphSpp)

# tests equal variance 
mDif = median(Control$StaphSpp) - median(Train$StaphSpp)
Train$StaphSppScaled = Train$StaphSpp + mDif

ansari.test(Train$StaphSppScaled, Control$StaphSpp, conf.level = 0.95, paired = F)
var(Control$StaphSpp)
var(Train$StaphSpp)
```


# Staph Aureus
```{r}
Train = subset(x, Trt == "Train" & StaphAureus != "NA" )
Control = subset(x, Trt == "Control" & StaphAureus != "NA")

## test of asymmetry
test = RFPW(Train$StaphAureus) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$StaphAureus) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$StaphAureus, Control$StaphAureus, paired = F)
SIGN.test(Train$StaphAureus, conf.int = T)
SIGN.test(Control$StaphAureus, conf.int = T)

# tests equal distribution functions
ks.test(Train$StaphAureus, Control$StaphAureus, exact = NULL)

# tests equal location and scale
pLepage(Train$StaphAureus, Control$StaphAureus)

# tests equal variance 
mDif = median(Control$StaphAureus) - median(Train$StaphAureus)
Train$StaphAureusScaled = Train$StaphAureus + mDif

ansari.test(Train$StaphAureusScaled, Control$StaphAureus, conf.level = 0.95, paired = F)
var(Control$StaphAureus)
var(Train$StaphAureus)
```

# Rods 
```{r}
Train = subset(x, Trt == "Train" & Rods != "NA" )
Control = subset(x, Trt == "Control" & Rods != "NA")

## test of asymmetry
test = RFPW(Train$Rods) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$Rods) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$Rods, Control$Rods, paired = F)
SIGN.test(Train$Rods, conf.int = T)
SIGN.test(Control$Rods, conf.int = T)

# tests equal distribution functions
ks.test(Train$Rods, Control$Rods, exact = NULL)

# tests equal variance 
mDif = median(Control$Rods) - median(Train$Rods)
Train$RodsScaled = Train$Rods + mDif

ansari.test(Train$RodsScaled, Control$Rods, conf.level = 0.95, paired = F)
var(Control$Rods)
var(Train$Rods)
```

# Gram positive cocci
```{r}
Train = subset(x, Trt == "Train" & GramPosCocci != "NA" )
Control = subset(x, Trt == "Control" & GramPosCocci != "NA")

## test of asymmetry
test = RFPW(Train$GramPosCocci) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$GramPosCocci) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$GramPosCocci, Control$GramPosCocci, paired = F)
SIGN.test(Train$GramPosCocci, conf.int = T)
SIGN.test(Control$GramPosCocci, conf.int = T)

# tests equal distribution functions
ks.test(Train$GramPosCocci, Control$GramPosCocci, exact = NULL)

# tests equal variance 
mDif = median(Control$GramPosCocci) - median(Train$GramPosCocci)
Train$GramPosCocciScaled = Train$GramPosCocci + mDif

ansari.test(Train$GramPosCocciScaled, Control$GramPosCocci, conf.level = 0.95, paired = F)
var(Control$GramPosCocci)
var(Train$GramPosCocci)
```


# Strepp spp
```{r}
Train = subset(x, Trt == "Train" & StrepSpp != "NA" )
Control = subset(x, Trt == "Control" & StrepSpp != "NA")

## test of asymmetry
test = RFPW(Train$StrepSpp) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

test = RFPW(Control$StrepSpp) # asymmetric
pnorm(test$obs.stat)
1- pnorm(test$obs.stat)

wilcox.test(Train$StrepSpp, Control$StrepSpp, paired = F)
SIGN.test(Train$StrepSpp, conf.int = T)
SIGN.test(Control$StrepSpp, conf.int = T)

# tests equal distribution functions
ks.test(Train$StrepSpp, Control$StrepSpp, exact = NULL)

# tests equal variance 
mDif = median(Control$StrepSpp) - median(Train$StrepSpp)
Train$StrepSppScaled = Train$StrepSpp + mDif

ansari.test(Train$StrepSppScaled, Control$StrepSpp, conf.level = 0.95, paired = F)
var(Control$StrepSpp)
var(Train$StrepSpp)
```


